version: "2.4"
services:
  myback:
    container_name: myback
    build: .
    volumes:
      - /data.txt
    restart:
      always
  myfront:
    container_name: myfront
    build: ./frontend
    restart:
      always


